public enum AudioClipName
{
    Bgm_Castle = 0,
    Bgm_Field = 1,
    Bgm_Puyo = 2,
    Bgm_Spelunk = 3,
    UnityChan_Aha1 = 4,
    UnityChan_Aha2 = 5,
    UnityChan_Aha3 = 6,
    UnityChan_Aha4 = 7,
    UnityChan_Aha5 = 8,
    UnityChan_Clear = 9,
    UnityChan_Goal = 10,
    UnityChan_Hoe = 11,
    UnityChan_ItemGet = 12,
    UnityChan_None = 13,
    UnityChan_Soret = 14,
    UnityChan_Start = 15,
    UnityChan_Yang = 16,
    UnityChan_Yat = 17,
}
